2025-05-20 00:21:50,431 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 938997ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 02:19:54,110 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 6911933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 02:37:23,854 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 938504ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 02:54:54,678 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 940279ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 04:58:11,273 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 7212313ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 05:11:44,196 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 698898ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 07:12:51,187 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 7118010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 07:25:18,077 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 674089ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 08:13:58,048 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 2899455ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 09:15:05,068 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 3646902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 10:16:12,135 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 3646577ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 10:32:59,985 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 987539ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 11:17:18,992 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 2638329ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 12:18:25,952 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 3646451ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 13:19:32,877 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 3646661ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 13:34:56,978 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 903785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 14:20:34,453 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 2737386ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 15:13:35,104 ERROR 7475 nodejs.ClusterClientNoResponseError: client no response in 3160510ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 7475
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 18:18:46,604 ERROR 56577 [-/::1/-/15ms POST /process-markdown] Markdown 处理失败: Error: ENOENT: no such file or directory, open '/Users/zuohuaihan/Desktop/归档/z-blog-server/articles/demo.md'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at MarkdownService.processMarkdown (/Users/zuohuaihan/Desktop/归档/z-blog-server/app/service/markdown.js:17:40)
    at MarkdownController.processMarkdown (/Users/zuohuaihan/Desktop/归档/z-blog-server/app/controller/markdown.js:46:56)
    at Object.callFn (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/egg-core@5.5.1/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/egg-core@5.5.1/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/@eggjs+router@2.2.0/node_modules/@eggjs/router/lib/utils.js:17:21)
    at wrappedController (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/@eggjs+router@2.2.0/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/koa-compose@3.2.1/node_modules/koa-compose/index.js:44:32)
    at next (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/koa-compose@3.2.1/node_modules/koa-compose/index.js:45:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/zuohuaihan/Desktop/归档/z-blog-server/articles/demo.md'
}
2025-05-20 18:19:19,434 ERROR 56644 [-/::1/-/15ms POST /process-markdown] Markdown 处理失败: Error: ENOENT: no such file or directory, open '/Users/zuohuaihan/Desktop/归档/z-blog-server/公众号开发流程(嵌入h5)--入门上手.md'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at MarkdownService.processMarkdown (/Users/zuohuaihan/Desktop/归档/z-blog-server/app/service/markdown.js:17:40)
    at MarkdownController.processMarkdown (/Users/zuohuaihan/Desktop/归档/z-blog-server/app/controller/markdown.js:46:56)
    at Object.callFn (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/egg-core@5.5.1/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/egg-core@5.5.1/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/@eggjs+router@2.2.0/node_modules/@eggjs/router/lib/utils.js:17:21)
    at wrappedController (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/@eggjs+router@2.2.0/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/koa-compose@3.2.1/node_modules/koa-compose/index.js:44:32)
    at next (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/koa-compose@3.2.1/node_modules/koa-compose/index.js:45:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/zuohuaihan/Desktop/归档/z-blog-server/公众号开发流程(嵌入h5)--入门上手.md'
}
2025-05-20 20:45:20,351 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 90331ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 20:47:51,431 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 151035ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 20:50:02,410 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 130948ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 20:57:13,871 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 411443ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 21:44:09,725 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 2815762ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-20 22:46:32,819 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 3722638ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

2025-05-21 00:46:47,817 ERROR 56417 nodejs.ClusterClientNoResponseError: client no response in 7214051ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/zuohuaihan/Desktop/归档/z-blog-server/node_modules/.pnpm/cluster-client@3.7.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
name: "ClusterClientNoResponseError"
pid: 56417
hostname: zuohuaihandeMacBook-Pro.local

